{% set version = "1.0.1" %}

package:
  name: tomoatt
  version: {{ version }}

source:
  url: https://github.com/TomoATT/TomoATT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e94b465f341bdbb5f09c5205baf82087663d3defa1c6b03106646dba2422e64c

build:
  number: 0
  skip: true  # [win or (osx and x86_64)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - openmpi
    - hdf5 =*=mpi_openmpi*
    - yaml-cpp
    - pytomoatt

test:
  commands:
    - cd test && sh run_this_example.sh

about:
  home: https://tomoatt.com
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Adjoint-state Travel-Time Tomography
  dev_url: https://github.com/TomoATT/TomoATT

extra:
  recipe-maintainers:
    - xumi1993
