{% set version = "1.0.2" %}

package:
  name: tomoatt
  version: {{ version }}

source:
  url: https://github.com/TomoATT/TomoATT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65c6f28af9231e831eef18b9de28284fe882cf24e56b2a671ebc5d2e9fdc5feb

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - openmpi
  host:
    - openmpi
    - hdf5 =*=mpi_openmpi*
    - yaml-cpp
    - pytomoatt

test:
  commands:
    - cd test && sh run_this_example.sh

about:
  home: https://tomoatt.com
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Adjoint-state Travel-Time Tomography
  dev_url: https://github.com/TomoATT/TomoATT

extra:
  recipe-maintainers:
    - xumi1993
