{% set version = "1.1.0" %}

package:
  name: tomoatt
  version: {{ version }}

source:
  url: https://github.com/TomoATT/TomoATT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b85b9c02456a22eb801f8a3bdb8e677b1c976b6887053bbbf24caff954a38ac7

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - openmpi
    - {{ mpi }}  
  host:
    - {{ mpi }}
    - hdf5 =*=mpi_openmpi*
    - yaml-cpp
    - pytomoatt

test:
  commands:
    - cd test && sh run_this_example.sh

about:
  home: https://tomoatt.com
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Adjoint-state Travel-Time Tomography
  dev_url: https://github.com/TomoATT/TomoATT

extra:
  recipe-maintainers:
    - xumi1993
