{% set version = "1.1.2" %}

package:
  name: tomoatt
  version: {{ version }}

source:
  url: https://github.com/TomoATT/TomoATT/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9127cf5f5f12ef0b02fe5a4c4042723c4af7044085c1bdce24b09af4a16c0410

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - openmpi >=4.1,<5.0  # [not osx_arm64]
    - openmpi >=5.0       # [osx_arm64]
  host:
    - openmpi >=4.1,<5.0  # [not osx_arm64]
    - openmpi >=5.0       # [osx_arm64]
    - hdf5 =*=mpi_openmpi*
    - yaml-cpp

test:
  requires:
    - pytomoatt
  commands:
    - cd test && sh run_this_example.sh

about:
  home: https://tomoatt.com
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Adjoint-state Travel-Time Tomography
  dev_url: https://github.com/TomoATT/TomoATT

extra:
  recipe-maintainers:
    - xumi1993
