build_platform:
  linux_64: linux_64
  osx_arm64: osx_arm64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_64: default
  osx_arm64: default
