build_platform:
  linux_64: linux_64
  linux_aarch64: linux_64
  osx_arm64: osx_arm64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
provider:
  linux_64: azure
  osx_arm64: azure
  linux_aarch64: default
os_version:
  linux_64: cos7
  linux_aarch64: cos7
