build_platform:
  linux_64: linux_64
  osx_arm64: osx_arm64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_64: azure
  osx_arm64: azure
